# DB config
# User and db creation done in mysql role

- name: Check if mysql tables are already created
  shell: 'mysql -u dts4user -p{{dts_mysql_password}} dts4 --execute="show tables"'
  register: dts4_db_tables
  changed_when: false

- name: Insert target-connection.xml
  template: src=target-connection.xml.j2
            dest={{dts_install_dir}}/bin/kb/target-connection.xml

- name: Create dts schema
  shell: ./kbcreate.sh
  args:
   chdir: "{{dts_install_dir}}/bin/kb/create"
  when: not dts4_db_tables.stdout.find('Tables_in_dts4') != -1
         
# TODO: Optionally import database here

# Config Jboss Standalone here

- name: Insert dts configs for JBoss
  template: src={{item.src}}
            dest={{item.dest}}
  with_items:
   - { src: 'application-roles.properties.j2', dest: '{{dts_jboss_home_dir}}/standalone/configuration/application-roles.properties' }
   - { src: 'application-users.properties.j2', dest: '{{dts_jboss_home_dir}}/standalone/configuration/application-users.properties' }
   - { src: 'mgmt-users.properties.j2', dest: '{{dts_jboss_home_dir}}/standalone/configuration/mgmt-users.properties' }
   - { src: 'standalone-apelondts-mysql.xml.j2', dest: '{{dts_jboss_home_dir}}/standalone/configuration/standalone.xml' }
   - { src: 'application-roles.properties.j2', dest: '{{dts_jboss_home_dir}}/domain/configuration/application-roles.properties' }
   - { src: 'application-users.properties.j2', dest: '{{dts_jboss_home_dir}}/domain/configuration/application-users.properties' }
   - { src: 'mgmt-users.properties.j2', dest: '{{dts_jboss_home_dir}}/domain/configuration/mgmt-users.properties' }
  notify: restart jboss

- meta: flush_handlers

- name: Copy deployments to JBoss
  jboss: src={{item.src}}
         deployment={{item.deployment}}
         deploy_path={{dts_jboss_home_dir}}/standalone/deployments
         state=present
  with_items:
   - { src: '{{dts_install_dir}}/lib/mysql-connector-java.jar', deployment: 'mysql-connector-java.jar'}
   - { src: '{{dts_install_dir}}/server/jboss/standalone/deployments/dtsjboss.ear', deployment: 'dtsjboss.ear'}
